//GIT RESET:
///SOFT RESET: RESETTING BASED ON STAGE
///HARD RESET: RESETTING COMMITS AND UNCOMMITTED CHANGES

//FOLDER HARUS MASUK UNTUK CEK STATUS

//KODE HASH GIT: KODE/ID DI GITHUB, CAN BE USED WHEN WANT TO RESET
//.gitignore: IGNORE FILES IN FOLDER TO NOT BE COMMITTED IN REPOSITORY, BENTUKNYA FILE (HARUS DIBUAT) DAN NAMA FILE DIMASUKKAN DI DALAM .gitignore (MISALNYA UNTUK FILE ENVIRONTMENT ATAU FILE PACKAGE INSTALL DENGAN DIZE BESAR)
//GIT TAGGING: BISA MEMBUAT TAG DI COMMIT, BENTUKNYA git tag -a [TAG NAME] -m [TAG DESCRIPTION]

//IT IS NOT SUGGESTED TO DO UPDATES DIRECTLY ON MAIN BUT BRANCHES, ONCE THE BRANCH IS READY/CLEAN THEN IT CAN BE MERGED TO MAIN
//IT IS SUGGESTED TO ADD-COMMIT-PUSH EVERYTIME A CHANGE IS DONE
//MAKE A BRANCH: git checkout -b [BRANCH NAME]
//MERGE BRANCH TO MAIN: git merge [BRANCH NAME] OR GO TO PULL REQUEST
///PULL REQUEST: 
//IT IS SUGGESTED TO PULL BEFORE DOING ANY CHANGES